### ISSUE TITLE
Depending on CloudState Protocols in Language Supports

### ISSUE THREAD

**Issue by viktorklang** [cloudstateio/cloudstate#118]
We need a solution for how language-supports when given their own repositories will depend on the CloudState Protocols from this repository.

Publish a zip-archive of the protos? What solutions are out there?

**Comment by marcellanz** [comment]
Great point; having possibly many language support libraries and all of them have different module/dependency packaging formats and support, a ZIP file might be a great way to upstream them towards a language support lib.

Comparing other projects, the protobuf project itself distributes the proto files with their releases:
https://github.com/protocolbuffers/protobuf/releases
and within their *.proto files and options, like `option java_package`, for all supported languages are included. These [options](https://developers.google.com/protocol-buffers/docs/proto3#options) might be exists also for language support libs of CloudState ( https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/empty.proto#L35-L41 as an example)

Regarding of possible duplication and/or re-distribution of proto files through projects depending on them, it seems to be non-consistent even on official gRPC plugins itself. 

For Dart and as an example for the well known empty.proto file, the Dart gRPC Plugin project has similar requests to include these well known proto files into the plugin itself:
https://github.com/protocolbuffers/protobuf/issues/5678
https://github.com/dart-lang/protobuf/issues/170#issuecomment-460067703

because it does not have them included.

On the other side, the Go plugin has them with the go grpc plugin and `go get ...`-ing the grpc plugin of go installs them on the relevant GOPATH so developers can use them.

With CloudState Language Support libs, they might be responsible if and how to provide CloudState *.proto files and perhaps having them even pre-compiled for the user.

**Comment by ihostage** [comment]
@viktorklang What about move protocol to separate repository and use Git Submodules for this repository and all other language support repositories?

**Comment by viktorklang** [comment]
@ihostage That's a very valid idea. My main reservation [against] is whether people would be comfortable with that setup.

**Comment by ihostage** [comment]
@viktorklang Yep, it isn't an easy way for maintainers 😄Just I don't know the unify artifact format, that will be a good fit for all supported languages. But your idea about zip-archive maybe 🤔Need more thoughts from members 😄

**Comment by viktorklang** [comment]
@ihostage One option might be to publish it as a FileDescriptorSet?

**Comment by ihostage** [comment]
@viktorklang Dynamic Messages has less performance than real code, generated by `protoc`. I think that will be much better if artifact will contain `.proto` files.

**Comment by viktorklang** [comment]
@ihostage The proxy cannot contain the user function protos since it will only know what they are at runtime.

**Comment by marcellanz** [comment]
@viktorklang @ihostage Regarding the options what and how to distribute the CloudState protocol:

As a maintainer, I'd prefer to get the original `*.proto` files of the CloudState procotol in the form they are used for the spec or in other documentation. From there, the upstream support library might handle the inclusion, or non inclusion of them for their users in a way most idiomatic to their language ecosystem.
Hence, if one decides to compile the `*.proto` files into the target language source code, or any other suitable format, and include them to a built artefact, it might be the right way for them. The source of truth of the protocol lies in the most original form of it, in our case the `*.proto` files, and CloudState can or might not know how to do that. WDYT?

**Comment by viktorklang** [comment]
Agreed. Perhaps we should just make a zip-archive and make it downloadable, perhaps even putting it behind a CDN or similar if need be.

**Comment by ihostage** [comment]
If we move protocol to separate repository, we can use GitHub out-of-box feature and get zip-archive with `*.proto` files by next URL:
`https://github.com/cloudstateio/<protocol-repository>/archive/vX.Y.Z.zip`

**Comment by marcellanz** [comment]
This could even be solely a repo to build the zip artefact where a script gets the proto files from the main repository so that they're not moved out of it and then the github release feature is used to generate the Zip files.

But also, as the projects aim is to be a _"A standards effort"_ and "A reference implementation", the main CloudState repo itself, the standards effort could be captured separately with such a repo.

If someone comes along and implements an alternative to the reference implementation in C++, the protocols repo would be a dependency it would depend on. In this terms, the reference implementation (https://github.com/cloudstateio/cloudstate) is nothing more than an another consumer of the protocol repo.

Perhaps others also have an opinion if a separate repo makes sense at this stage of the project.

**Comment by viktorklang** [comment]
Not sure it helps to pull the reference implementation out at this point, since we still need to build the TCK etc.

**Comment by marcellanz** [comment]
@viktorklang Is this still an issue? #153 provided a zip file built on releases and depending language suppotrt libraries can get them versioned as documented now.

**Comment by viktorklang** [comment]
Good catch, @marcellanz!
