### ISSUE TITLE
Start FAQ.md doc

### ISSUE THREAD

**Issue by jboner** [cloudstateio/cloudstate#26]
Discussing things like: 
- Why CRUD is too unconstrained to work well
- How Akka Cluster work under the hood
- etc.

**Comment by rstento** [comment]
Fairly simple task if we simply iink to explanations elsewhere.

**Comment by rstento** [comment]
The Cloudstate doc motivates event sourcing here: https://cloudstate.io/docs/crud-limitations.html & https://cloudstate.io/docs/concepts/eventsourced.html. I couldn't find much about Akka clustering or sharding, @jboner, should we rename this so that it concentrates on Akka clustering and cluster sharding?

**Comment by jboner** [comment]
That's fine.

**Comment by jboner** [comment]
If still needed. I would check with the team what they think is needed here.

**Comment by rstento** [comment]
@jroper & @pvlugter, WDYT about revising or closing this issue, see discussion above. Thanks!

**Comment by pvlugter** [comment]
I don't think we need or want full explanations of how Akka works in the Cloudstate docs, since it's meant to be independent of Akka. Looks like the entity descriptions already mention sharding as needed. We could add links to where Akka Cluster and Akka Persistence are referenced. Otherwise, I think it's fine to close this issue now, given the motivation sections in the docs already.

**Comment by rstento** [comment]
@pvlugter, I don't have permission to close in this repo, would you please?

thanks!
