### ISSUE TITLE
Input CloudState/community Gitter: tracking WIP on project.

### ISSUE THREAD

**Issue by marcellanz** [cloudstateio/cloudstate#300]
A few days ago in CloudState/community Gitter the question came up, how "to have a list of main items going on and to specify what we want to work on". I reference the thread below go get context.
We placed that on the contributors call minutes so we can track it but we lost it as we are not all on the same call most of the time. I herein open the topic here to discuss.

I know that a lot is going on and now as even more contributors or anyone willing to help are joining, it its helpful go get a picture of whats going on.

For sure we should not increase ceremony more than needed, especially in this early phase of the project. But we could help a bit to get communicated whats going on.

Either if its "github project", Issues with labels, Issues assigned or even milestones planned, WDYT about the topic @viktorklang @jroper @hseeberger ?

(ping @ralphlaude @sleipnir)

Gitter:
<img width="966" alt="Screenshot 2020-05-06 at 09 08 59" src="https://user-images.githubusercontent.com/12616445/81146774-3ae32180-8f79-11ea-85ae-ed258cb4757f.png">

Meetings note:
<img width="638" alt="Screenshot 2020-05-06 at 09 06 08" src="https://user-images.githubusercontent.com/12616445/81146643-01121b00-8f79-11ea-9da8-e069a51c8d83.png">

**Comment by pvlugter** [comment]
Thanks @marcellanz. I wasn't aware of the earlier discussion, but I've also been thinking about this, and discussed earlier in the week with @viktorklang.

So, continue to have more visibility (and discussion) in issues, probably do some more with labels, assign issues, prioritise and make the upcoming tasks visible in milestones (which can also have issues ordered). And have a simple project board, with something like `Ready`, `In Progress`, `Review`, and `Done`, to make the workflow obvious. Proposed issues or issues to discuss could be added there too — I've found that works well, as issues can easily be added and removed from the board.

I was already going to start adding some of this process, as we do for other projects at Lightbend, for visibility. I don't think it adds unnecessary overhead or ceremony, but makes it easier to collaborate and understand what's going on. Sounds like there's already consensus on this being useful :+1:

**Comment by marcellanz** [comment]
@pvlugter awesome! (missed you in the list, sorry).

This sounds great and I'm happy you guide us through this and let us know how we can help :) We'll have the situation to connect items between repos (lang support), where I don't know yet how to track that. But let's find out that as we do it.

**Comment by marcellanz** [comment]
@pvlugter awesome! (missed you in the list, sorry).

This sounds great and I'm happy you guide us through this and let us know how we can help :) We'll have the situation to connect items between repos (lang support), where I don't know yet how to track that. But let's find out that as we do it.

**Comment by ralphlaude** [comment]
@marcellanz very good to bring this topic back 👍 , i agree. I am happy to help if needed.

**Comment by ralphlaude** [comment]
@pvlugter good proposal with the project board 👍

**Comment by pvlugter** [comment]
> We'll have the situation to connect items between repos (lang support), where I don't know yet how to track that. But let's find out that as we do it.

Yes. I've started by creating an org-level project, rather than repo-level, which is linked to the main cloudstate repo and the support repos:

https://github.com/orgs/cloudstateio/projects/1

I'll set up more tomorrow, like shared access to this via teams. We can see how it goes to have this as a common board across everything.

**Comment by pvlugter** [comment]
There's some automation on the columns, if an issue is added to the project it will go to the To do list, if a PR is added then it gets added to the Review list automatically, when issues or PRs are closed they get moved to Done automatically, and so on.

**Comment by sleipnir** [comment]
Hello guys! I'm glad it was addressed so well

**Comment by pvlugter** [comment]
I've created some teams for managing access to repositories, and for all contributors to be part of the organization for access to the shared project board. Teams can also be `@`-mentioned, to make it easier to mention groups of people as needed.

@cloudstateio/core-team : @jroper @viktorklang @hseeberger @pvlugter 

@cloudstateio/go-team : @marcellanz 

@cloudstateio/kotlin-team : @sleipnir 

@cloudstateio/dart-team : @sleipnir 

@cloudstateio/dotnet-team : 

And all these teams are subteams of @cloudstateio/contributors 

The language support teams have Maintain permissions on the relevant support repo. Please let me know if anyone is missing access to something. I've just used the contributor access on repositories to create the teams. Let me know if there are other maintainers that should be added.

**Comment by viktorklang** [comment]
Good call, @pvlugter—thanks!

I think you can set @nagytech as on the dotnet-team?

**Comment by pvlugter** [comment]
> I think you can set @nagytech as on the dotnet-team?

@nagytech, invited you to the dotnet team

**Comment by marcellanz** [comment]
thank you @pvlugter, 👍

**Comment by sleipnir** [comment]
Thanks @pvlugter

**Comment by pvlugter** [comment]
I expect the process is already obvious, but this is my view on it:

* Tasks should have an issue (in the appropriate repo).

* Each module will usually have a milestone for the next version, and planned issues are added to this milestone. The milestone lets us all see upcoming work, and makes it easy to track what was worked on for a version, once completed. Note: milestone issues can also be ordered, if useful. The main cloudstate repo will have separate milestones for the modules (protocol, proxy, java support, node support) since these are on different release cycles. See the [go-support v0.2.0 milestone](https://github.com/cloudstateio/go-support/milestone/1) as an example.

* If you're planning to work on an issue, assign yourself.

* You can add upcoming tasks to the **To do** list on the Cloudstate project board (we probably don't want everything there, just the top couple of issues from upcoming milestones).

* Move the issue to  the **In progress** list once you start working on it.

* When you open a PR, please reference its associated issue (usually with the auto-closing form of `Fixes #123` or `Resolves #123`, or just reference it to not have the issue auto-close). On the project board, issue cards will automatically display any linked PRs. Issues and/or PRs are moved/added to the **Review** list, when ready for review. Draft PRs can be used to share work-in-progress.

* Once PRs are merged, they'll usually auto-close the associated issue, and be moved to **Done** automatically. We'll periodically archive the cards under Done.

The project board should provide shared visibility into the workflow and work-in-progress.

I've also added an extra **Discuss** column at the end of the board; let's see if that becomes a useful way to add issues for discussion. Also, markdown notes can be added to project boards, for anything that doesn't make sense as a full issue. If a link to an outside repo is added to a note, then it gets converted into an issue-style card—useful for any repos that are not under the cloudstateio org. We're still to evolve the labels that are used on issues; that can be ongoing and iterative.

And as a general guideline, let's prefer the master branches to be in a ready-to-release state. Usually, changes should only be merged when they're "done" (have tests, docs, suggested changes are resolved, and so on). It makes it easier to track development. We can easily use feature branches, if work on something needs to be ongoing and spread over multiple PRs. For the main cloudstate repo, I've added some basic merge requirements as a reminder: CI build passing and at least 1 review approval.

Since the project board is set up, I'll close this issue for now.

**Comment by marcellanz** [comment]
@pvlugter thank you for these excellent guidelines written. perhaps we can have them captured in a CONTRIBUTING.md file or the like.

**Comment by ralphlaude** [comment]
@pvlugter thanks for the guidelines

**Comment by hseeberger** [comment]
@pvlugter thanks for the writeup!

**Comment by viktorklang** [comment]
@pvlugter Sounds great!

**Comment by pvlugter** [comment]
> perhaps we can have them captured in a CONTRIBUTING.md file or the like.

Good idea to start building up a CONTRIBUTING.md. I can make a start on this.
