### ISSUE TITLE
Golang Support

### ISSUE THREAD

**Issue by kwehden** [cloudstateio/cloudstate#80]
Where is a good entrypoint for folks interested in Golang contributions to clients slide?

**Comment by marcellanz** [comment]
@kwehden I'd say:
- build the project
- read the docs
- understand the protocol
- generate the proto/grpc stubs for Go
- wire TCK with the Go implementation
- run the TCK and see it failing
- implement EntityDiscovery
- run the TCK and see it still failing
... implement any of the other services
Beside that, studying the Java/JS implementation helps too.

**Comment by viktorklang** [comment]
Also depends a bit on whether it is an API-first or a protocol-first approach,
but if I was doing the Go support I'd start by coming up with an idiomatic Go API based on looking at the Java and JavaScript Shopping Cart samples (since those are used by the TCK).

After having created an idiomatic Go API and implemented the Shopping Cart app with it, I'd then generate a gRPC Server for the Entity protocol (https://github.com/cloudstateio/cloudstate/blob/master/protocols/protocol/cloudstate/entity.proto)

Then I'd implement the Entity Protocol.

Then add the Go Shopping Cart as a TCK permutation and run that to validate what works and doesn't.

Then I'd iterate on top of running the TCK and implementing support for the EventSourced protocol (https://github.com/cloudstateio/cloudstate/blob/master/protocols/protocol/cloudstate/event_sourced.proto)

Then the CRDT protocol and the funciton protocol etc.

**Comment by viktorklang** [comment]
I've pushed (to master) some better explanation to TCK verification failures, to better help guide implementation of the protocol. Enjoy!

**Comment by marcellanz** [comment]
Thanks, I'll try it today.

(BTW EntityDiscovery#reportError was helpful in similar cases, where the proxy informed the client what he expects when it was not sent properly by the client)

**Comment by viktorklang** [comment]
@marcellanz Cool. Yeah, reportError was a slick addition by @jroper. Once we have a bit more bandwidth we should start nailing down a formal specification of the protocol.

**Comment by marcellanz** [comment]
@viktorklang nice. I found the .proto files most of the time very valuable and accurate.
Only when something was not obiviously clear I visited the implementation. I can list the points where it was the case.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by viktorklang** [comment]
Closing this in favor of #3

**Comment by viktorklang** [comment]
@marcellanz Would love to get your feedback there!
